# Generated by Django 4.2.6 on 2023-11-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pettype', models.CharField(max_length=100)),
                ('petage', models.IntegerField()),
                ('ownedbefore', models.CharField(max_length=300)),
                ('plantoprovide', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=300)),
                ('emergencycontact', models.CharField(max_length=12)),
                ('emergencyemail', models.EmailField(max_length=100)),
                ('acknowledge', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
