# Generated by Django 4.2.6 on 2023-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
