# Generated by Django 4.2.6 on 2023-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', editable=False, max_length=20),
        ),
    ]
