# Generated by Django 4.2.6 on 2023-11-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='app_status',
        ),
    ]
