# Generated by Django 4.2.6 on 2023-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("location", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("shelter", models.CharField(max_length=100)),
                ("status", models.CharField(default="Available", max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "pets",
                    models.ManyToManyField(
                        related_name="collections", to="pet_listings.pets"
                    ),
                ),
            ],
        ),
    ]
