# Generated by Django 4.2.6 on 2023-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
