# Generated by Django 4.2.6 on 2023-11-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listings', '0002_alter_pets_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pets',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pets',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pets',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pets',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pets',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='pets',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pets',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
