# Generated by Django 4.2.6 on 2023-11-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listings', '0003_pets_breed_pets_color_pets_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='pets',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=100),
        ),
    ]
