# Generated by Django 4.2.6 on 2023-11-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petseeker',
            name='applications',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
